name: MVP sneakers Git CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 3
      matrix:
        python-version: [ 3.10.6 ]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint  lxml pylint-report flake8-html
          poetry install --no-root

      - name: Create directories
        run: |
          mkdir -p reports/dags/flake8/
          mkdir -p reports/dags/pylint/

      - name: Lint with flake8
        run: |
          flake8 dags || flake8 dags  --format=html --htmldir=reports/dags/flake8/

      - name: Lint with pylint
        run: |
          pylint dags || pylint dags --output-format=pylint_report.CustomJsonReporter --load-plugins = "pylint_report"  | pylint_report > reports/dags/pylint/report.html | false


      - name: Upload reports
        if: ${{ failure() }}
        uses: actions/upload-artifact@v3
        with:
          name: html_reports
          path: reports/
